# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 231345c4a059632a12f46b464372e9fd054dfa081c86912cd147e08ac37a1686683e66f9dccf8bc13e85c515386379223c19c50ca69048139151b52f6761f695

test:
  secret_key_base: 3adc087b5e8e3f935ba62794019a9ca25ab9560811f6dba1ec8a0377cbfd31fc9951a33b1e7f9581a35a884aa4a2be5cbe93786adee3772d4a2f7d3c22dc00d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
